#!/usr/bin/expect -f
set passToHash [lindex $argv 0]
set server_ip [lindex $argv 1]
set rsi_password [lindex $argv 2]
set root_password [lindex $argv 3]
set hashedPass [ exec bash -c "echo -n \"$passToHash\" | sha256sum | tr -d \" -\""]
set filename [lindex $argv 4]
spawn ssh "rsiadmin@$server_ip"
expect {
	-re "Password:" {
		send "$rsi_password\r"
		exp_continue
		}
	 "$ " {
		send "su\r"
		}
	-re "yes/no" {
		send "yes\r"
		exp_continue
		}
}
expect {
	-re "Password:" {
		send "$root_password\r"
		exp_continue
		}
	 "# " {
		send "systemctl stop graylog-server && systemctl stop elasticsearch\r"
		}

} 
expect {
	"# " {
		send "sed -i \"s/.*root_password_sha2.*/root_password_sha2 = $hashedPass/\" \"$filename\"\r"
	}
}
expect {
	"# " {
		send "systemctl start elasticsearch ; systemctl start graylog-server\r" 
	}
}
expect {
	"# " {
		send "exit\r" 
	}
}
expect {
	"$ " {
		send "exit\r"
	}
} 
expect eof
